-- CreateTable
CREATE TABLE "Order" (
    "id" SERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "sku" TEXT NOT NULL,
    "qtySmall" INTEGER NOT NULL DEFAULT 0,
    "qtyMedium" INTEGER NOT NULL DEFAULT 0,
    "qtyLarge" INTEGER NOT NULL DEFAULT 0,
    "qtyXL" INTEGER NOT NULL DEFAULT 0,
    "qty2X" INTEGER NOT NULL DEFAULT 0,
    "qty3X" INTEGER NOT NULL DEFAULT 0,
    "expectedDate" TIMESTAMP(3) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Draft',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Order_pkey" PRIMARY KEY ("id")
);
